version: "3"
services:
  portfolio:
    build:
      context: .
    volumes:
      - ./:/app:ro
    working_dir: /app
    environment:
      ALPHAPOOL_DATABASE_URL: 'postgresql://postgres:password@host.docker.internal/postgres'
      ALPHAPOOL_LOG_LEVEL: ${ALPHASEA_LOG_LEVEL:-debug}
      ALPHAPOOL_EXECUTION_COST: ${ALPHAPOOL_EXECUTION_COST:-0.001}
      ALPHAPOOL_OPTIMIZATION_DAYS: ${ALPHAPOOL_OPTIMIZATION_DAYS:-60}
      ALPHAPOOL_MAX_LEVERAGE: ${ALPHAPOOL_MAX_LEVERAGE:-5}
      ALPHAPOOL_SCORE_THRESHOLD: 0.5
      ALPHAPOOL_INTERVAL: 300
      ALPHAPOOL_PORTFOLIO: ${ALPHAPOOL_PORTFOLIO:-equal_weight}
      ALPHAPOOL_MODEL_ID: ${ALPHAPOOL_MODEL_ID:-pf-model1}
    command: ['python', '-m', 'src.main_simple']
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
